Setup-Your-Mac-via-Dialog.bash
Updates the `loggedInUserFirstname`  variable to handle fullnames in both formats: "Firstname Lastname" and "Lastname, Firstname"
=> Allow "first name" to correctly handle names in "Lastname, Firstname" format

Setup-Your-Mac-via-Dialog.bash
The Dialog fails to open if the banner/welcome images are not available. We use this to test the image URLs and set an alternative image if the default fails. Folks can add a second custom image as a backup.
Resubmit of: #21
=> check bannerImage & welcomeBannerImage - resubmit

Setup-Your-Mac-via-Dialog.bash
Function used to send failure and success notifications to a Microsoft Teams channel via an incoming webhook.
=> Added sendWebhookMessage function

Setup-Your-Mac-via-Dialog.bash
Adjusted previous "promptFor_" toggles to line up with other toggles in the script Add a commented out option to disable Blur screen on production runs Added a handful of Branding overrides
Primary goal is to cut down on modifications needed by those adapting this script down the line.
=> Additional User Input Flags

Setup-Your-Mac-via-Dialog.bash, Validations/Check Printer Install.sh, Validations/Microsoft Office 365.bash
Add Remote Validation results of "Success" or "Installed" to update the List Item with "Installed" instead of "Running"
Change existing Validations for Printers and Office 365 to return "Installed" instead of "Running"
=> Remote Validation Changes

Setup-Your-Mac-via-Dialog.bash
Added a flag to hide the Banner Text.  Handy if the Banner Image has text in it already.
=> Option to disable Banner Text

Setup-Your-Mac-via-Dialog.bash
Added a direct link to the computer record in Jamf Pro for Slack webhooks
=> Add button to computer record for Slack webhook

Setup-Your-Mac-via-Dialog.bash
After using Erase All Content And Settings on a Mac that has had a RSR installed the RSR persists.
This change will report the subversion (a) (b) etc. in the script logs as well as anywhere else `osVersion` is called in the main script.
Can be held for 1.10.1 as LineNumbers have been shifted.
I primarily wrote this to report RSR value in the Webhook results.
=> Report on RSR version if applicable

Setup-Your-Mac-via-Dialog.bash
I added a minimum version check to the `dialogCheck` function and split out the SwiftDialog install portion to it's own function as it is now used twice.
Log output on a machine with an outdated version "`2.1.0.4148`" of SwiftDialog
```
2023-05-28 19:21:27 - PRE-FLIGHT CHECK: # # # SETUP YOUR MAC VERBOSE DEBUG MODE: Line No. 414 # # #
2023-05-28 19:21:28 - PRE-FLIGHT CHECK: swiftDialog version 2.1.0.4148 found but swiftDialog 2.2 or newer is required; updating...
2023-05-28 19:21:28 - PRE-FLIGHT CHECK: Installing SwiftDialog...
installer: Package name is
installer: Upgrading at base path /
installer: The upgrade was successful.
2023-05-28 19:21:32 - PRE-FLIGHT CHECK: swiftDialog version 2.2.0.4535 installed; proceeding...
2023-05-28 19:21:32 - PRE-FLIGHT CHECK: Complete
```
Log output …
=> Add version check to dialogCheck, Split out install to new function

Setup-Your-Mac-via-Dialog.bash
Fix for visual hiccup where the infobox stays on "Analyzing input" if `configurationDownloadEstimation` and `promptForConfiguration` are both set to false.
Preserves intended behavior when `promptForConfiguration` is false and `configurationDownloadEstimation` is true.
=> Infobox User Input Visual Hiccup

Setup-Your-Mac-via-Dialog.bash
Add the option to disable Recon on policy runs while not defaulting to that.
Attempts to address issue brought up in #79 
minimal testing on this one.
=> Add Support for Suppressing Recon on Policy Runs

Setup-Your-Mac-via-Dialog.bash
Created new variables to each configuration for install buffers
Added the calculation to add buffer to estimated time for presenting to user
=> Added Install Buffers to each configuration

Setup-Your-Mac-via-Dialog.bash
Fixing the dialogURL location to the new repo url, also added -L to the curl command for good measure.
=> change dialogURL to new Github Repo

Setup-Your-Mac-via-Dialog.bash
Currently the toggleJamfLaunchDaemon trigger is commented out in the QuitScript function but should be executed if the CompletionActionOption results in the Mac not being shut down or restarted. This PR adds an if statement to check if the CompletionActionOption is one where the ToggleJamfLaunchDaemon function should be triggered
=> toggleJamfLaunchDaemon based on CompletionActionOption

Setup-Your-Mac-via-Dialog.bash
Do you hear that your users are forcing through the setup too quickly, perhaps clicking wrong things, or not making informed decisions on how long the configurations are going to take? How often do you hear them say "this process takes too long" only to find out they picked your most complete configuration and have no idea what you're talking about when you ask how long did the estimations take? Do you wish your users would just wait the few seconds for the estimations to appear before clicking through your input requirements? Well now you can make that happen, with the all new "Lock Continue Button" option!
If you set the "lockContinueBeforeEstimations" variable to true, the "continue" button (button1 of the dialog window, it doesn't matter what text was given for it) will be disabled …
=> Lock continue button until estimations are complete

Setup-Your-Mac-via-Dialog.bash
Added a check to account for if the loggedInUser returns in all caps, as this sometimes happens with SSO Attributes.
Previously, if the name was in all caps, it stayed that way when presenting the dialog to the user: 
With the added check in the loggedInUserFirstname, it now looks to see if the name is in all caps and corrects the case, while also still working for other cases: 
=> Updated loggedInUserFirstname

Setup-Your-Mac-via-Dialog.bash
Adding If switches to only include existing support values.
My use case here is that I don't have either KB articles or a support cell phone number that would work here.
Hopefully this proves useful going forward in accommodating other similar use cases.
With values: 
Without Values:
=> Hiding unused Support Variables

Setup-Your-Mac-via-Dialog.bash
This is a simple pre-flight check to validate that at least one of the support Vars & supportTeamName are filled in as discussed with Dan.
=> PreFlightCheck for Support Vars

Setup-Your-Mac-via-Dialog.bash
This adds a failure indication when a "Local" validation trigger does not exist in the main script.
It marks the policy as failed even if the preceding trigger succeeded as it is unable to be properly validated.
The list status text reflects the missing validation so the end user can alert support as well.
=> Add failure indication for local validation catch all

Setup-Your-Mac-via-Dialog.bash
This PR adds functionality to let admins override the overlayicon dynamically based on which configuration is selected by the end user.
To use, an admin sets `overlayoverride` in any of policyJSON case statements EX L947
The original overlayicon is shown briefly and then updated with the icon defined in `overlayoverride`
To skip changing the overlay icon leave the default of `overlayoverride=""`
This PR should satisfy #110 
swiftDialog does not support dynamically updating the banner image. I will look at providing a bespoke solution for this.
=> Add OverlayIcon override code.

Setup-Your-Mac-via-Dialog.bash
Adds the current build number to the webhook output of Teams and Slack.
**NOTE:** Please Test! This is currently untested as I can't call the webhook without doing an actual install.
=> Added OS Build number to webhook output

Setup-Your-Mac-via-Dialog.bash
This PR should satisfy #129
Refactored the way the `brandingBanner` variable is checked. Script now only caches remote resources if they are https URLs. Local files are simply piped to the rest of the script so this should cut down on unwanted network requests.
This needs extra testing as quite a bit of code was changed. Seems to work fine in my limited DEBUG testing.
=> brandingBanner Refactor

Setup-Your-Mac-via-Dialog.bash
It seems that if `bannerText` is set to nothing `=""` then the `title="blah"` parameter takes over.
Fix is to set `bannerText=" "` instead of `bannerText=""` when `brandingBannerDisplayText="false"`
=> Fix brandingBannerDisplayText=false not working

Setup-Your-Mac-via-Dialog.bash
Thanks to @fabienconus, swiftDialog `2.5.6` now includes the ability to `hide:` or `show:` a running dialog (which does not prevent window updates from occurring when the dialog is hidden).
While I (currently) doubt we would ever use this in our production environment, others may benefit from allowing end-users to directly interact with apps installed as part of SYM.
A new `tigger` of `none` has been added to leverage the new `validation` options:
-  `Blurscreen On`
- `Blurscreen Off`
- `Hide Dialog`
- `Show Dialog`
In each of the four Configurations:
1. Before **Palo Alto GlobalProtect** is installed, the blurscreen is disabled via `"trigger": "none",` and `"validation": "Blurscreen Off"`:
```
{
"listitem": "Palo Alto GlobalProtect",
"subtitle": "Virtual Private Network (VPN) connection …
```
=> `hide` or `show` Proof-of-concept
